AjaxProject/urls.py
from django.urls import path
from .views import photo_add_view


app_name= 'AjaxProject'
urlpatterns = [

    path('ajax', photo_add_view, name="ajax"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include ('users.urls',       namespace='users'         )),
    path('', include ('food.urls',        namespace='food'          )),
    path('', include ('AjaxProject.urls', namespace='AjaxProject'   )),   
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    # import debug_toolbar
    
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    #     ]+urlpatterns


    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from .views import (
    burger,
    pizza, 
    index,
    order,
    )


app_name = 'food'
urlpatterns = [
    path('', index, name="index" ),
    path('burger', burger, name="burger" ),
    path('pizza', pizza, name="pizza"),
    path('order', order, name="order" ),


]

users/urls.py
from django.urls import path
from .views import signup, login_n, logout_n


app_name= 'users'
urlpatterns = [
    path('signup', signup, name="signup"),
    path('login', login_n, name="login"),
    path('logout', logout_n, name="logout"),
]

AjaxProject/models.py
from django.db import models

class Photo(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='profile')
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

food/models.py
from django.db import models



class Pizza(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.DecimalField(max_digits=4, decimal_places=2)
    priceL = models.DecimalField(max_digits=4, decimal_places=2)
    pImage = models.URLField()
    

class Burger(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.DecimalField(max_digits=4, decimal_places=2)
    priceL = models.DecimalField(max_digits=4, decimal_places=2)
    bImage = models.URLField()
    

users/models.py
from django.db import models

# Create your models here.

AjaxProject/forms.py
from django import forms
from .models import Photo

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('image','name','description')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    # i will modify email
    email = forms.EmailField(max_length=120, required=True, help_text='Enter  a valid email address')
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

AjaxProject/views.py
from django.shortcuts import render
from .forms import PhotoForm
# let return a Json Response
from django.http import JsonResponse









def photo_add_view(request):
    template_name = 'AjaxProject/index.html'
    form = PhotoForm(request.POST or None, request.FILES or None)
    data ={} #data dictionary is going to be empty initialy if below is valid we can add something to it 
    if request.is_ajax():
        if form.is_valid():
            form.save()
            data['name'] = form.cleaned_data.get('name')
            data['status'] = 'ok'
            return JsonResponse(data)
    context = {'form': form}
    return render(request, template_name, context)

food/views.py
from django.shortcuts import render
from .models import Pizza, Burger
#from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required



#@staff_member_required

def index (request):
    template_name ='food/index.html'
    
    context={'active_link':'index'}
    return render (request, template_name, context)


@login_required(login_url='users:login')
def burger (request):
    template_name ='food/burger.html'
    queryset = Burger.objects.all()
    context={
        'queryset': queryset,
        'active_link':'burger'
        }
    return render (request, template_name, context)


@login_required(login_url='users:login')
def pizza (request):
    template_name = 'food/pizza.html'
    queryset= Pizza.objects.all()
    context= {
        'queryset': queryset,
        'active_link':'pizza'
        }
    return render (request, template_name, context)


@login_required(login_url='users:login')
def order (request):
    template_name ='food/orders.html'
    
    context={'active_link':'orders'}
    return render (request, template_name, context)

users/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
#from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages




def signup(request):
    template_name = "users/sign-up.html"

    form = NewUserForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('users:login')
    context = dict( form =NewUserForm())
    return render(request, template_name, context)


def login_n(request): # i change login 
    template_name ='users/login.html'
    
    if request.POST:
        username = request.POST.get('username')
        pwd      = request.POST.get('password')
        
        user = authenticate(request, username=username, password=pwd)
        if user is not None: # which means is authenticate
            login(request, user)# this login is a django function
            return redirect('food:index')
    else:
        messages.info(request, 'username and/or password are incorrect')
        #messages.info(request, 'Three credits remain in your account.')
    context ={'active_link': 'login'}
    return render (request, template_name, context)
    
    
def logout_n(request):
    logout(request)
    return redirect('food:index')

AjaxProject/templates/AjaxProject/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} Ajax Form {% endblock title %}



{% block content %}
<link rel="stylesheet" href="{% static 'ajax/css/style.css' %}">


<div class="container">
<h1>AJAX</h1>
<div id="alert-box"></div>
<div id="img-box"></div>


<form  id="p-form">
    {% csrf_token %}
    
    {{form|crispy}}

</form>

<button class="btn btn-primary" type="submit">Submit</button>
</div>



<script src="{% static 'ajax/js/main.js' %}"></script>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block style %} {% endblock style %}
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <!-- Local css -->
    <link rel="stylesheet" href="{% static 'food/css/style.css' %}">
    
    <!-- Font aewesome  -->
    <link rel="stylesheet" href="">

    <title>{% block title %} Document {% endblock title %} | RUTH RESTAUTANT</title>
    
   
</head>
<body>
    
    
    {% include 'navbar.html' with brand_name='Ruth Restaurant' %}
    


    {% block content %}

    {% endblock content %}






        <!--Jquery library  from Hosted Libraries-->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    

    <!-- Jquery Librairy  -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" ></script> 
    
    <!-- Popper Js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" ></script>
    
    <!-- Latest Compiled Js -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>
    
    <!-- Local Js -->
    <script src="{% static 'food/js/main.js' %}"></script>
</body>
</html>

templates/food/burger.html
{% extends 'base.html' %}
{% load static %}




{% block title %} Burger {% endblock title %}

{% block content %}

<!-- div for image below -->
<!-- <div class="home"></div>  -->

<style>
    .picture{
        width: 200px;
        height: 160px;
        border-radius: 50%;
    }

    
</style>


<div class="container-fluid">
<div class="row text-center">
    <div class="col-md-8">
        <h2 class="title mb-5"> Burger </h2>
        <div class="row">
            
            {% for burger in queryset %}
            <div class="col-md-4 mb-3">
                <img class="picture"  src="{{ burger.bImage }}" alt="">
                <h4 class="pt-3" id="bur{{burger.id}}">{{ burger.name }}</h4>
                <div class="form-check-inline">
                    <label class="form-check-label ">
                        <input class="form-check-input" type="radio" name="burger{{ burger.id }}" value="{{ burger.priceM }}" checked>
                        {{ burger.priceM }}
                    </label>
                </div>

                <div class="form-check-inline">
                    <label class="form-check-label">
                        <input class="form-check-input " type="radio" name="burger{{ burger.id }}" value="{{burger.priceL }}">
                        {{ burger.priceL }}
                    </label>
                </div>

                <div>
                    <button class="btn-info mt-3" onclick="addBurger('{{ burger.id }}')">Add to cart </button>
                </div>

            </div>
            {% endfor %}
        </div>

    </div>
    <div class="col-4 orders">
        <div class='bg-dark text-light p-2 rounded'>
            <h2 class="text-center">Order List</h2>
            <ul id="bcart"></ul>
            <h4 class="text-right" id="btotal">Total: 0 $</h4>
        </div>
    </div>
</div>
</div>

<script src="{% static 'food/js/burgers.js' %}"></script>

{% endblock %}

templates/food/index.html
{% extends 'base.html' %}


{% block content %}

    <div class="container">
        <h1>INDEX</h1>
    </div>
    


{%  endblock %}

templates/food/orders.html
{% extends 'base.html' %}
{% load static %}




{% block title %} orders {% endblock title %}



{% block content %}

<div class="container-fluid m-4">
    <div class="row">
        <div class="col-md-6 text-center">
            <h2>Orders</h2>
            <div class="row">
                <div class="col-md-3" id="name">
                    <h3>Name</h3>
                </div>
                <div class="col-md-3" id="size">
                    <h3>Size</h3>
                </div>
                <div class="col-md-3" id="price">
                    <h3>Price</h3>
                </div>
                <div class="col-md-1 " id="rm">

                </div>
        
            </div>
            <h2 id="total">Total:</h2>

        </div>
        <!-- <div class="col-md-1" id="rm">

        </div> -->
       
        <div class="col-md-5">
            <h2>Message</h2>
            <textarea name="message" id="message" cols="40" rows="5"></textarea>
            <div class=" mt-2">
            <button type="submit" class="btn btn-success" onclick="order()"> Submit</button>
        </div>
        </div>
    </div>
</div>

<script src="{% static 'food/js/cart.js' %}"></script>
{% endblock content %}

templates/food/pizza.html
{% extends 'base.html' %}
{% load static %}


{% block title %} pizza {% endblock title %}


{% block content %}

<link rel="stylesheet" href="{% static 'food/css/orders.css' %}">


<div class="container-fluid">
    <div class="row ">
        <div class="col-md-8 text-center">
            <h2 class="title mb-5"> Pizza </h2>
            <div class="row">
                
                {% for pizza in queryset %}
                <div class="col-md-4 mb-3">
                    <img class="picture"  src="{{ pizza.pImage }}" alt="">
                    <h4 class="pt-3" id='piz{{ pizza.id }}'>{{ pizza.name }}</h4>

                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio"  value="{{ pizza.priceM }}"  name="pizza{{ pizza.id }}" checked>
                        <label class="form-check-label" for="inlineCheckbox0">M:{{pizza.priceM}}$ </label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" name="pizza{{ pizza.id }}" type="radio"  value="{{ pizza.priceL }}" >
                        <label class="form-check-label" for="inlineCheckbox1">L:{{pizza.priceL}}$ </label>
                    </div>

                    <div>
                        <button class="btn-info mt-3" onclick="addPizza('{{ pizza.id }}')">Add to cart </button>
                    </div>

                </div>
                {% endfor %}
            </div>

        </div>
        <div class="col-4 orders">
            <div class='bg-dark text-light p-2 rounded'>
                <h2 class="text-center">Order List</h2>
                <ul id="pcart"></ul>
                <h4 class="text-right" id="ptotal">Total: 0 $</h4>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'food/js/order.js' %}"></script>

{%  endblock %}

templates/navbar.html
{% load static %}

{% url 'exercise:home' as home_url %}
{% url 'exercise:contact'  as contact_url %}
{% url 'products:product' as product_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
        <!-- navbrand -->
    <a class="navbar-brand" href="{{ home_url }}">
        <!-- <img src="#" alt="" width="50"
                    height="50" class="d-inline-block align-top"> -->
        {% if brand_name %} {{ brand_name }} {% else %} Mpoyi's eCommerce {% endif %}    
    </a>
    <!-- end nav brand -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item ">
                <a class="nav-link {% if active_link == 'index' %} active {% endif %}" href="{% url 'food:index' %}"  >Home </a>
                
            </li>
            <li class="nav-item ">
                <a class="nav-link {% if active_link == 'pizza' %} active {% endif %}" href="{% url 'food:pizza' %}">Pizza </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link {% if active_link == 'burger' %} active {% endif %}" href="{% url 'food:burger' %}">Burgers</a>
            </li>
        </ul>

            <!-- put this part of navbar at the right handside -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
                <!-- put the link of the orders in by shoping cart  -->
                <a href="{% url 'food:order' %}" class="nav-link {% if active_link == 'orders' %} active {% endif %}" >
                    <img src="https://img.icons8.com/fluent/35/000000/shopping-cart-promotion.png"/><span id="cart"></span></a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <h5 class="text-light pt-2 pr-4 "> Welcome {{user.username}}</h5>
            </li>
            {% endif %}

            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link " href="{% url 'users:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link  {% if active_link == 'login' %} active {% endif %}"   href="{% url 'users:login' %}" href="#">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'users:signup' %}">Register</a>
            </li>
        
            {% endif %}
        </ul>
        {% include 'search/snippet/search-form.html' %}
    </div>
</div>
</nav>

templates/search/snippet/search-form.html
<!-- <form method="GET" action="#" class="form my-2 my-lg-0">
    <div class="input-group">
        <input class="form-control " type="search" name="q" placeholder="Search" value='{{ request.GET.q }}'>
        value make the text stay in the search bar
        <span class='input-group-btn'>
                <button class="btn btn-outline-success " type="submit">Search</button>
            </span> 
    </div> 
</form> -->

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} LOGIN {% endblock title %}


{% block content %}

<!-- style -->
<link rel="stylesheet" href="{% static 'users/css/style.css' %}">
    
<div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-3"> </div><!--first grid-->
            <div class="col-md-6 p-5 bg-dark text-light text-center">
                <h3> LOGIN </h3>
                <form action="" method="POST" novalidate>
                    {% csrf_token %}

                    
                    <div class="form-group">
                        <input type="text" name="username" placeholder="Username">
                    </div>

                    
                    <div class="form-group">
                    <input type="password" name="password" placeholder="***********">
                    </div>
                    
                    
                    <button type="submit" class="btn-info">Submit </button>
                    {% if messages %}
                    <ul class='pt-2 text-center'>
                        {% for message in mesages %}
                            <li style="color:red">{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </form>
                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Don't have an account? <a href="{% url 'users:signup' %}" class="ml-2">Sign Up</a>

                    </div>
                </div>

                
            </div>
            <div class="col-md-3">

            </div>

            
        </div>
    
    </div>
    


{%  endblock %}

templates/users/sign-up.html
{% extends 'base.html' %}
{% load static %}

{% block title %} SiGN UP {% endblock title %}


{% block content %}

<!-- style -->
<link rel="stylesheet" href="{% static 'users/css/style.css' %}">
    
<div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-3"> </div><!--first grid-->
            <div class="col-md-6 p-2 bg-dark text-light text-center">
                <h4> REGISTER ACCOUNT</h4>
                <form action="" method="POST" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group"><!--inside form goup 2 div for label and form field-->
                        <div><!--1st div-->
                            {{field.label_tag}}
                        </div>
                        <div><!--2nd div-->
                            {{field}}
                        </div>
                        <!-- {% if field.help_text %}
                            <small style="color:grey">{{ field.help_text}}</small> 
                            {% endif %}  -->
                    </div>
                    {% endfor %}
                    <div>
                    {% for error in form.errors %}
                        <small style='color:red'>{{ error }}</small>
                    {% endfor %}
                    </div>
                    <button type="submit" class="btn-info">Submit </button>
                </form>
                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Already have an account? <a href="{% url 'users:login' %}"
                            class="ml-2"> Login</a>                    
                    </div>
                </div>
            </div>
           
            <div class="col-md-3">

            </div>

            
        </div>
    
    </div>
    


{%  endblock %}